-- Sample data for run_clubs table
-- Run this in your Supabase SQL Editor after creating the table

INSERT INTO run_clubs (id, name, description, location, state, suburb, coordinates, meeting_day, meeting_time, time_of_day, difficulty, distance_focus, contact_email, website, instagram, created_at, updated_at) VALUES
(
  '1',
  'Sydney Harbour Runners',
  'Scenic runs around the beautiful Sydney Harbour with views of the Opera House and Harbour Bridge. All fitness levels welcome!',
  'Circular Quay, Sydney NSW 2000',
  'NSW',
  'Sydney',
  '{"lat": -33.8688, "lng": 151.2093}',
  'Wednesday',
  '6:00 AM',
  'morning',
  'intermediate',
  ARRAY['5K', '10K'],
  'info@sydneyharbourrunners.com.au',
  'https://sydneyharbourrunners.com.au',
  '@sydneyharbourrunnersau',
  '2024-01-01T00:00:00Z',
  '2024-01-01T00:00:00Z'
),
(
  '2',
  'Bondi Beach Morning Runners',
  'Start your day with an energizing run along the iconic Bondi Beach. Perfect for early risers and beach lovers.',
  'Bondi Beach, Bondi NSW 2026',
  'NSW',
  'Bondi',
  '{"lat": -33.8915, "lng": 151.2767}',
  'Saturday',
  '6:30 AM',
  'morning',
  'beginner',
  ARRAY['5K', 'Mixed'],
  'hello@bondiruns.com.au',
  NULL,
  '@bondibeachrunners',
  '2024-01-01T00:00:00Z',
  '2024-01-01T00:00:00Z'
),
(
  '3',
  'Melbourne Park Run Club',
  'Exploring Melbourne''s beautiful parks and gardens. Family-friendly group with post-run coffee sessions.',
  'Royal Botanic Gardens, Melbourne VIC 3004',
  'VIC',
  'Melbourne',
  '{"lat": -37.8304, "lng": 144.9803}',
  'Sunday',
  '8:00 AM',
  'morning',
  'beginner',
  ARRAY['5K', '10K'],
  'contact@melbourneparkrun.com.au',
  'https://melbourneparkrun.com.au',
  NULL,
  '2024-01-01T00:00:00Z',
  '2024-01-01T00:00:00Z'
),
(
  '4',
  'Brisbane River Runners',
  'Follow the scenic Brisbane River paths through the heart of the city. Great for marathon training and socializing.',
  'South Bank Parklands, Brisbane QLD 4101',
  'QLD',
  'South Brisbane',
  '{"lat": -27.4733, "lng": 153.0176}',
  'Thursday',
  '6:15 AM',
  'morning',
  'intermediate',
  ARRAY['10K', 'Half Marathon', 'Marathon'],
  'info@brisbaneriverrunners.com.au',
  NULL,
  '@brisbaneriverrunners',
  '2024-01-01T00:00:00Z',
  '2024-01-01T00:00:00Z'
),
(
  '5',
  'Perth Kings Park Pacers',
  'Train in one of the world''s largest inner-city parks with stunning city views and native bushland trails.',
  'Kings Park, Perth WA 6005',
  'WA',
  'Perth',
  '{"lat": -31.9505, "lng": 115.8605}',
  'Tuesday',
  '6:00 AM',
  'morning',
  'advanced',
  ARRAY['10K', 'Half Marathon'],
  'hello@perthkingspark.com.au',
  'https://perthkingsparkpacers.com.au',
  NULL,
  '2024-01-01T00:00:00Z',
  '2024-01-01T00:00:00Z'
); 